name: dawal2
description: "Dawal version Android studio 20240209."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+5
#
environment:
  sdk: '>=3.2.6 <4.0.0'
#
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Liens
  url_launcher: ^6.2.4
  # json
  json_annotation: ^4.8.1
  # Audio
  just_audio: ^0.9.36

###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  ######## fait le 20240209 ############
  flutter_launcher_icons: ^0.13.1
  http: ^1.2.0
  # json
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
#
flutter:
  uses-material-design: true

  ######## fait le 20240123 ############
  fonts:
    - family: Amazigh tms
      fonts:
        - asset: assets/fonts/MZTIMENR.TTF
    - family: Amazigh arial bold
      fonts:
        - asset: assets/fonts/MZARIALB.TTF
  #
  assets:
    - assets/images/
    - assets/images/lettres/
    - assets/audio_lettres/
    - assets/audio_exemples/
    - assets/json/lettres.json
